env: 
  dev102

server:
  port: '8082'
spring:
  redis:
    host: 192.168.99.100
    port: 6379
    timeout:  1000
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=utf-8&useSSL=false
    username: root
  cloud:
    stream:
      bindings:
        input-message:
          group:  order
          content-type: application/json
    
    #spring.cloud.stream.bindings.input-message.group=order
